name: Update Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install sphinx sphinx-autobuild
        pip install sphinx_rtd_theme
    - name: Rebuild
      run: cd docs && make html
    - uses: jakejarvis/s3-sync-action@v0.5.1
      name: Upload
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'docs/_build/html'
        DEST_DIR: 'itpp.dev/chat/'
